#!/usr/bin/env bash

__cd_dir () {
  local git_top_level
  git_top_level="$(git rev-parse --show-toplevel 2>/dev/null)"

  if [ "$git_top_level" = "$HOME" ]; then
    cd "$PWD"
  else
    cd "$git_top_level"
  fi

  # shellcheck disable=SC2164
}

trap bash EXIT

__cd_dir

