#!/usr/bin/env bash

__cd_dir () {
  local git_top_level
  git_top_level="$(git rev-parse --show-toplevel 2>/dev/null)"

  # shellcheck disable=SC2164
  if [ "$git_top_level" = "$HOME" ]; then
    # shellcheck disable=SC2164
    cd "$PWD"
  else
    # shellcheck disable=SC2164
    cd "$git_top_level"
  fi

}

executable=bash
if [ Darwin = "$(uname)" ]; then
  executable=/opt/homebrew/bin/bash
fi
trap "exec $executable" EXIT

__cd_dir

